//
// Created by bobi on 15. 9. 26.
//

#include "McGen/McGen.h"

#include <cctype>
#include <climits>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <set>

#include "ImcGen/data/expr/ImcBINOP.h"
#include "ImcGen/data/expr/ImcCALL.h"
#include "ImcGen/data/expr/ImcCONST.h"
#include "ImcGen/data/expr/ImcMEM.h"
#include "ImcGen/data/expr/ImcNAME.h"
#include "ImcGen/data/expr/ImcSEXPR.h"
#include "ImcGen/data/expr/ImcTEMP.h"
#include "ImcGen/data/expr/ImcUNOP.h"
#include "ImcGen/data/stmt/ImcCJUMP.h"
#include "ImcGen/data/stmt/ImcCMD.h"
#include "ImcGen/data/stmt/ImcESTMT.h"
#include "ImcGen/data/stmt/ImcJUMP.h"
#include "ImcGen/data/stmt/ImcLABEL.h"
#include "ImcGen/data/stmt/ImcMOVE.h"
#include "ImcGen/data/stmt/ImcSTMTS.h"
#include "ImcLin/ImcLin.h"
#include "Memory.h"
#include "McGen/McPeephole.h"
#include "ImcOpt/Liveness.h"
#include "Utils/Colors/Font.h"

namespace Basic {
    namespace {
        std::string dimText(const std::string &text) {
            return Utils::Font::colorDim + text + Utils::Font::colorReset;
        }

        std::string score(const std::string &holder) { return holder + " mcl"; }

        // As short as it can be written: "3", "37.5", "0.001".
        std::string decimal(double value) {
            std::string s = std::to_string(value);
            s.erase(s.find_last_not_of('0') + 1);
            if (s.back() == '.')
                s.pop_back();
            return s == "-0" ? "0" : s;
        }

        std::string lower(std::string text) {
            for (char &c : text)
                c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
            return text;
        }

        // Saving pushes onto `saved`; restoring pops in the reverse order.
        std::vector<std::string> saveLines(const std::string &holder) {
            return {"execute store result storage mcl:mem tmp int 1 run scoreboard players get " + score(holder),
                    "data modify storage mcl:mem saved append from storage mcl:mem tmp"};
        }

        std::vector<std::string> restoreLines(const std::string &holder) {
            return {"execute store result score " + score(holder) + " run data get storage mcl:mem saved[-1]",
                    "data remove storage mcl:mem saved[-1]"};
        }

        void append(std::vector<std::string> &to, const std::vector<std::string> &lines) {
            to.insert(to.end(), lines.begin(), lines.end());
        }
    }

    // ---- driver --------------------------------------------------------------

    bool McGen::generate(const std::string &outDir) {
        m_errors.clear();
        m_files.clear();
        m_data.clear();
        m_peephole = 0;
        m_saves = 0;
        m_clobbers.clear();
        m_commands.clear();

        // Globals sit back to back from DATA_START, each a whole number of slots.
        long long next = DATA_START;
        for (const LinDataChunk &data : m_lin.dataChunks()) {
            if (data.init)
                error("string data ('" + data.label.name + "') is not supported in the datapack yet");
            m_data[data.label.name] = next;
            next += static_cast<long long>((data.size + SLOT_SIZE - 1) / SLOT_SIZE * SLOT_SIZE);
        }

        if (m_optimize)
            computeClobbers();

        bool hasMain = false, hasTick = false;
        for (const LinCodeChunk &chunk : m_lin.codeChunks()) {
            hasMain = hasMain || chunk.frame->label == "main";
            hasTick = hasTick || chunk.frame->label == "tick";
            genChunk(chunk);
        }
        addRuntime(hasMain, hasTick);
        addEntries();
        if (!m_errors.empty())
            return false;

        namespace fs = std::filesystem;
        const fs::path root(outDir);
        fs::remove_all(root / "data" / "mcl"); // only ever generated code lives here

        writeFile((root / "pack.mcmeta").string(),
                  {R"({"pack": {"pack_format": 48, "supported_formats": {"min_inclusive": 48, "max_inclusive": 99},)",
                   R"(          "description": "Generated by MCLang"}})"});
        const fs::path tags = root / "data" / "minecraft" / "tags" / "function";
        writeFile((tags / "load.json").string(), {R"({"values": ["mcl:load"]})"});
        // Everything in the tick tag runs every game tick, 20 times a second.
        if (hasTick)
            writeFile((tags / "tick.json").string(), {R"({"values": ["mcl:tick"]})"});
        else
            fs::remove(tags / "tick.json"); // left over from an earlier build

        std::size_t commands = 0;
        for (const auto &[path, lines] : m_files) {
            writeFile((root / "data" / "mcl" / "function" / (path + ".mcfunction")).string(), lines);
            std::size_t count = 0;
            for (const std::string &line : lines)
                count += !line.empty() && line[0] != '#';
            commands += count;
            if (m_print)
                std::cout << "  " << "mcl:" << path << dimText(" (" + std::to_string(count) + " commands)")
                          << std::endl;
        }
        if (m_print)
            std::cout << "  " << dimText(std::to_string(m_files.size()) + " functions, "
                                         + std::to_string(commands) + " commands, "
                                         + std::to_string(m_peephole) + " peephole rewrites, "
                                         + std::to_string(m_saves) + " temp saves at calls") << std::endl;
        return true;
    }

    void McGen::writeFile(const std::string &path, const std::vector<std::string> &lines) const {
        std::filesystem::create_directories(std::filesystem::path(path).parent_path());
        std::ofstream out(path);
        for (const std::string &line : lines)
            out << line << '\n';
    }

    // The fixed parts of the pack: setup, the entry point and memory access.
    void McGen::addRuntime(bool hasMain, bool hasTick) {
        m_files["load"] = {
            "# Runs when the datapack loads.",
            "scoreboard objectives add mcl dummy",
            "scoreboard players set #scale mcl " + std::to_string(SCALE),
            "scoreboard players set #slot mcl " + std::to_string(SLOT_SIZE * SCALE),
            "scoreboard players set #neg mcl -1",
            hasMain ? R"(tellraw @a {"text":"MCLang datapack loaded -- run it with /function mcl:run","color":"green"})"
                    : R"(tellraw @a {"text":"MCLang datapack loaded","color":"green"})",
        };
        // A tick can fire before any entry point has set up memory.
        if (hasTick)
            append(m_files["load"], resetLines());

        if (hasMain) {
            std::vector<std::string> run = resetLines();
            run.insert(run.begin(), "# Fresh memory and stack, then call main.");
            run.push_back("function " + functionName("main"));
            append(run, resultLines("main"));
            m_files["run"] = std::move(run);
        }

        m_files["rt/load"] = {
            "# Macro: $mem <- slot $(slot). A slot never written makes the get fail, and a",
            "# failed command stores 0.",
            R"mc($execute store result score $mem mcl run data get storage mcl:mem ram."$(slot)")mc",
        };

        m_files["rt/store"] = {
            "# Macro: slot $(slot) <- $mem.",
            R"mc($execute store result storage mcl:mem ram."$(slot)" int 1 run scoreboard players get $mem mcl)mc",
        };
    }

    std::vector<std::string> McGen::resetLines() {
        return {
            "data modify storage mcl:mem ram set value {}",
            "data modify storage mcl:mem saved set value []",
            setLine("$SP", STACK_TOP * SCALE),
            setLine("$FP", 0),
            setLine("$RV", 0),
        };
    }

    std::vector<std::string> McGen::resultLines(const std::string &function) {
        return {
            "# Print RV as a decimal: sign, whole part, then three zero-padded digits.",
            opLine("$int", "=", "$RV"),
            R"(data modify storage mcl:out sign set value "")",
            R"(execute if score $int mcl matches ..-1 run data modify storage mcl:out sign set value "-")",
            "execute if score $int mcl matches ..-1 run " + opLine("$int", "*=", "#neg"),
            opLine("$frac", "=", "$int"),
            opLine("$int", "/=", "#scale"),
            opLine("$frac", "%=", "#scale"),
            R"(data modify storage mcl:out pad set value "")",
            R"(execute if score $frac mcl matches ..99 run data modify storage mcl:out pad set value "0")",
            R"(execute if score $frac mcl matches ..9 run data modify storage mcl:out pad set value "00")",
            R"(tellraw @a [")" + function + R"( returned ",{"nbt":"sign","storage":"mcl:out"},{"score":{"name":"$int","objective":"mcl"}},".",{"nbt":"pad","storage":"mcl:out"},{"score":{"name":"$frac","objective":"mcl"}}])",
        };
    }

    // /function mcl:grid {w:5,h:3} -- the arguments come in by name as a macro
    // compound. The entry point copies them into storage (a macro can only
    // splice text), reads each one back scaled to fixed point, and writes it into
    // the argument block at SP, where a call would have put it. The static link
    // at SP+0 is left 0: a top-level function has no outer frame.
    void McGen::addEntries() {
        for (const DeclPtr &d : m_program) {
            const auto *fun = dynamic_cast<const FunDecl *>(d.get());
            if (!fun)
                continue;

            // tick is run by the game, not typed in, and keeps memory between
            // ticks: only the stack is reset, never ram.
            if (fun->name == "tick") {
                if (!fun->params.empty())
                    error("'tick' is run every game tick, so it can't take parameters");
                m_files["tick"] = {
                    "# Runs every game tick (tags/function/tick.json).",
                    setLine("$SP", STACK_TOP * SCALE),
                    setLine("$FP", 0),
                    "function " + functionName("tick"),
                };
                continue;
            }

            bool numbers = true;
            std::string compound, reads;
            std::vector<std::string> writes;
            for (const Param &p : fun->params) {
                const auto *type = dynamic_cast<const AtomicType *>(p.type.get());
                const auto *access = dynamic_cast<const MemRelAccess *>(m_memory.accessOf(&p));
                if (!type || (type->prim != "float" && type->prim != "bool") || !access) {
                    numbers = false;
                    break;
                }
                compound += (compound.empty() ? "" : ",") + p.name + ":$(" + p.name + ")";
                const long long slot = (STACK_TOP + access->offset) / static_cast<long long>(SLOT_SIZE);
                writes.push_back("execute store result storage mcl:mem ram.\"" + std::to_string(slot)
                                 + "\" int 1 run data get storage mcl:args call." + p.name + " "
                                 + std::to_string(SCALE));
            }
            if (!numbers)
                continue; // records, arrays and references can't be typed in as a number

            // The entry's own file sits next to load and run, so those names are taken.
            const std::string path = functionName(fun->name).substr(std::string("mcl:fn/").size());
            if (path == "load" || path == "run" || path == "rt" || path == "fn") {
                error("function '" + fun->name + "' can't have an entry point: mcl:" + path
                      + " is part of the runtime");
                continue;
            }

            std::string usage = "/function mcl:" + path;
            if (!fun->params.empty())
                usage += " {" + std::regex_replace(compound, std::regex(R"(\$\((\w+)\))"), "<$1>") + "}";

            std::vector<std::string> lines = {"# " + usage};
            append(lines, resetLines());
            if (!fun->params.empty()) {
                lines.push_back("$data modify storage mcl:args call set value {" + compound + "}");
                append(lines, writes);
            }
            lines.push_back("function " + functionName(fun->name));

            const auto *ret = dynamic_cast<const AtomicType *>(fun->returnType.get());
            if (fun->returnType && !(ret && ret->prim == "void"))
                append(lines, resultLines(fun->name));
            m_files[path] = std::move(lines);
        }
    }

    // ---- per function --------------------------------------------------------

    void McGen::genChunk(const LinCodeChunk &chunk) {
        const MemFrame &frame = *chunk.frame;
        m_function = frame.label;
        m_exit = chunk.exit.name;
        m_blocks.clear();
        m_terminated = true;

        // Unoptimized, the callee keeps every temp it writes, so a recursive call
        // can't disturb its caller. Optimized, the caller keeps only the temps
        // still live after each call that the callee can overwrite.
        std::set<std::size_t> temps;
        std::vector<Liveness::Temps> liveOut;
        if (m_optimize) {
            liveOut = Liveness::liveOut(chunk);
        } else {
            for (const ImcStmtPtr &s : chunk.stmts)
                for (std::size_t id : Liveness::defs(*s))
                    temps.insert(id);
        }

        for (std::size_t i = 0; i < chunk.stmts.size(); ++i) {
            const ImcStmtPtr &s = chunk.stmts[i];
            if (const auto *label = dynamic_cast<const ImcLABEL *>(s.get())) {
                if (!m_blocks.empty() && !m_terminated)
                    emit("return run function " + blockName(label->label.name)); // fall through
                m_blocks.push_back({label->label.name, {}});
                m_terminated = false;
                continue;
            }
            if (m_blocks.empty() || m_terminated)
                continue; // after a jump and before the next label: never runs

            m_scratch = 0;
            emit("# " + s->toString());
            const std::vector<std::size_t> saves = m_optimize ? callSaves(*s, liveOut[i]) : std::vector<std::size_t>{};
            for (std::size_t id : saves)
                for (std::string &line : saveLines("$" + ImcTemp(id).toString()))
                    emit(std::move(line));
            s->accept(*this);
            for (auto id = saves.rbegin(); id != saves.rend(); ++id)
                for (std::string &line : restoreLines("$" + ImcTemp(*id).toString()))
                    emit(std::move(line));
            m_saves += saves.size();
        }
        if (!m_blocks.empty() && !m_terminated)
            emit("return 1");

        const long long size = static_cast<long long>(frame.size()) * SCALE;
        std::vector<std::string> entry = {
            "# " + frame.toString(),
            m_optimize ? "# prologue: keep the caller's FP" : "# prologue: keep the caller's FP and every temp this function writes",
        };
        append(entry, saveLines("$FP"));
        for (std::size_t id : temps)
            append(entry, saveLines("$" + ImcTemp(id).toString()));
        entry.push_back(opLine("$FP", "=", "$SP"));
        entry.push_back(addLine("$SP", -size));
        entry.push_back("function " + blockName(chunk.entry.name));
        entry.push_back("# epilogue");
        entry.push_back(addLine("$SP", size));
        for (auto id = temps.rbegin(); id != temps.rend(); ++id)
            append(entry, restoreLines("$" + ImcTemp(*id).toString()));
        append(entry, restoreLines("$FP"));

        const std::string prefix = "mcl:";
        m_files[functionName(m_function).substr(prefix.size())] = std::move(entry);
        for (Block &block : m_blocks) {
            if (m_optimize)
                m_peephole += McPeephole::run(block.lines);
            m_files[blockName(block.label).substr(prefix.size())] = std::move(block.lines);
        }
    }

    void McGen::computeClobbers() {
        std::unordered_map<std::string, std::set<std::string>> callees;
        for (const LinCodeChunk &chunk : m_lin.codeChunks()) {
            std::set<std::size_t> &writes = m_clobbers[chunk.frame->label];
            for (const ImcStmtPtr &s : chunk.stmts) {
                for (std::size_t id : Liveness::defs(*s))
                    writes.insert(id);
                if (const ImcCALL *call = Liveness::callIn(*s))
                    callees[chunk.frame->label].insert(call->label.name);
            }
        }

        // Grow each set by its callees' until nothing changes; recursion is fine.
        bool changed = true;
        while (changed) {
            changed = false;
            for (auto &[function, clobbers] : m_clobbers) {
                for (const std::string &callee : callees[function]) {
                    auto it = m_clobbers.find(callee);
                    if (it == m_clobbers.end() || &it->second == &clobbers)
                        continue;
                    const std::size_t before = clobbers.size();
                    clobbers.insert(it->second.begin(), it->second.end());
                    changed = changed || clobbers.size() != before;
                }
            }
        }
    }

    std::vector<std::size_t> McGen::callSaves(const ImcStmt &stmt, const std::set<std::size_t> &liveOut) const {
        const ImcCALL *call = Liveness::callIn(stmt);
        if (!call)
            return {};
        const Liveness::Temps result = Liveness::defs(stmt); // written after the call; restoring would undo it
        const auto it = m_clobbers.find(call->label.name);

        std::vector<std::size_t> out;
        for (std::size_t id : liveOut)
            if (!result.contains(id) && (it == m_clobbers.end() || it->second.contains(id)))
                out.push_back(id); // a function we don't know might write anything
        return out;
    }

    // ---- naming --------------------------------------------------------------

    // Resource locations are lower case, so an upper-case letter becomes `_` and
    // its lower-case form: `sumAll` -> `sum_all`.
    std::string McGen::functionName(const std::string &function) {
        std::string out = "mcl:fn/";
        for (char c : function) {
            if (std::isupper(static_cast<unsigned char>(c))) {
                out += '_';
                out += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
            } else {
                out += c;
            }
        }
        return out;
    }

    std::string McGen::blockName(const std::string &label) const {
        return functionName(m_function) + "/" + lower(label);
    }

    std::string McGen::jumpTo(const std::string &label) const {
        return label == m_exit ? "return 1" : "return run function " + blockName(label);
    }

    // ---- commands ------------------------------------------------------------

    std::string McGen::gen(ImcExpr &expr) {
        expr.accept(*this);
        return m_holder;
    }

    std::string McGen::scratch() { return "$e" + std::to_string(m_scratch++); }

    long long McGen::fixed(double value) {
        const double scaled = std::round(value * SCALE);
        if (scaled > INT_MAX || scaled < INT_MIN) {
            error("the number " + std::to_string(value) + " is too large for the datapack's fixed point");
            return 0;
        }
        return static_cast<long long>(scaled);
    }

    std::string McGen::setLine(const std::string &holder, long long value) {
        return "scoreboard players set " + score(holder) + " " + std::to_string(value);
    }

    std::string McGen::opLine(const std::string &dst, const char *op, const std::string &src) {
        return "scoreboard players operation " + score(dst) + " " + op + " " + score(src);
    }

    // `add` only takes a non-negative amount.
    std::string McGen::addLine(const std::string &holder, long long amount) {
        return amount < 0 ? "scoreboard players remove " + score(holder) + " " + std::to_string(-amount)
                          : "scoreboard players add " + score(holder) + " " + std::to_string(amount);
    }

    void McGen::copy(const std::string &dst, const std::string &src) {
        if (dst != src)
            emit(opLine(dst, "=", src));
    }

    void McGen::load(const std::string &address, const std::string &dst) {
        copy("$slot", address);
        emit(opLine("$slot", "/=", "#slot"));
        emit("execute store result storage mcl:args slot int 1 run scoreboard players get $slot mcl");
        emit("function mcl:rt/load with storage mcl:args");
        copy(dst, "$mem");
    }

    void McGen::store(const std::string &address, const std::string &value) {
        copy("$slot", address);
        emit(opLine("$slot", "/=", "#slot"));
        emit("execute store result storage mcl:args slot int 1 run scoreboard players get $slot mcl");
        copy("$mem", value);
        emit("function mcl:rt/store with storage mcl:args");
    }

    // A record or array moves one slot at a time.
    void McGen::copySlots(const std::string &dst, const std::string &src, std::size_t size) {
        const std::string from = scratch(), to = scratch(), value = scratch();
        for (std::size_t offset = 0; offset < size; offset += SLOT_SIZE) {
            const long long scaled = static_cast<long long>(offset) * SCALE;
            copy(from, src);
            emit(addLine(from, scaled));
            load(from, value);
            copy(to, dst);
            emit(addLine(to, scaled));
            store(to, value);
        }
    }

    // Work out every argument first, then write them all into the block at SP.
    void McGen::emitCall(ImcCALL &call) {
        std::vector<std::string> holders;
        for (std::size_t i = 0; i < call.args.size(); ++i) {
            if (call.sizes[i] > SLOT_SIZE) {
                auto *mem = dynamic_cast<ImcMEM *>(call.args[i].get());
                if (!mem) {
                    error("a record-sized argument that is not in memory: " + call.args[i]->toString());
                    holders.push_back("$e0");
                    continue;
                }
                holders.push_back(gen(*mem->addr)); // where the value is, to copy from
            } else {
                holders.push_back(gen(*call.args[i]));
            }
        }

        for (std::size_t i = 0; i < call.args.size(); ++i) {
            const std::string at = scratch();
            copy(at, "$SP");
            emit(addLine(at, static_cast<long long>(call.offsets[i]) * SCALE));
            if (call.sizes[i] > SLOT_SIZE)
                copySlots(at, holders[i], call.sizes[i]);
            else
                store(at, holders[i]);
        }
        emit("function " + functionName(call.label.name));
    }

    // ---- expressions ---------------------------------------------------------

    void McGen::visit(ImcCONST &e) {
        m_holder = scratch();
        emit(setLine(m_holder, fixed(e.value)));
    }

    void McGen::visit(ImcNAME &e) {
        auto it = m_data.find(e.label.name);
        if (it == m_data.end())
            error("NAME " + e.label.name + " is not a data label");
        m_holder = scratch();
        emit(setLine(m_holder, it == m_data.end() ? 0 : it->second * SCALE));
    }

    void McGen::visit(ImcTEMP &e) { m_holder = "$" + e.temp.toString(); }

    void McGen::visit(ImcMEM &e) {
        if (e.size > SLOT_SIZE)
            error("a " + std::to_string(e.size) + "B value used as a number: " + e.toString());
        const std::string address = gen(*e.addr);
        m_holder = scratch();
        load(address, m_holder);
    }

    void McGen::visit(ImcUNOP &e) {
        const std::string operand = gen(*e.expr);
        m_holder = scratch();
        if (e.oper == ImcUNOP::Oper::NEG) {
            copy(m_holder, operand);
            emit(opLine(m_holder, "*=", "#neg"));
        } else {
            emit(setLine(m_holder, 0));
            emit("execute if score " + score(operand) + " matches 0 run " + setLine(m_holder, SCALE));
        }
    }

    void McGen::visit(ImcBINOP &e) {
        const auto *wide = dynamic_cast<ImcMEM *>(e.fst.get());
        if (wide && wide->size > SLOT_SIZE) {
            error("comparing records or arrays is not supported in the datapack yet");
            m_holder = scratch();
            return;
        }

        if (m_optimize && multiplyByWhole(e))
            return;

        const std::string a = gen(*e.fst);
        const std::string b = gen(*e.snd);
        const std::string h = scratch();
        const std::string truth = setLine(h, SCALE);

        auto compare = [&](const char *op) {
            emit(setLine(h, 0));
            emit("execute if score " + score(a) + " " + op + " " + score(b) + " run " + truth);
        };

        switch (e.oper) {
            case ImcBINOP::Oper::ADD:
                copy(h, a);
                emit(opLine(h, "+=", b));
                break;
            case ImcBINOP::Oper::SUB:
                copy(h, a);
                emit(opLine(h, "-=", b));
                break;
            case ImcBINOP::Oper::MUL: {
                // a*b/SCALE, split so a*b never has to fit in an int:
                // (a/SCALE)*b + ((a%SCALE)*b)/SCALE -- exact with floored / and %.
                const std::string rest = scratch();
                copy(h, a);
                emit(opLine(h, "/=", "#scale"));
                emit(opLine(h, "*=", b));
                copy(rest, a);
                emit(opLine(rest, "%=", "#scale"));
                emit(opLine(rest, "*=", b));
                emit(opLine(rest, "/=", "#scale"));
                emit(opLine(h, "+=", rest));
                break;
            }
            case ImcBINOP::Oper::DIV: {
                // a*SCALE/b, split the same way: (a/b)*SCALE + ((a%b)*SCALE)/b.
                const std::string rest = scratch();
                emit("execute if score " + score(b)
                     + R"( matches 0 run tellraw @a {"text":"MCLang: division by zero","color":"red"})");
                copy(h, a);
                emit(opLine(h, "/=", b));
                emit(opLine(h, "*=", "#scale"));
                copy(rest, a);
                emit(opLine(rest, "%=", b));
                emit(opLine(rest, "*=", "#scale"));
                emit(opLine(rest, "/=", b));
                emit(opLine(h, "+=", rest));
                break;
            }
            case ImcBINOP::Oper::MOD: // both sides carry the same scale, so it cancels
                copy(h, a);
                emit(opLine(h, "%=", b));
                break;
            case ImcBINOP::Oper::LTH: compare("<"); break;
            case ImcBINOP::Oper::GTH: compare(">"); break;
            case ImcBINOP::Oper::LEQ: compare("<="); break;
            case ImcBINOP::Oper::GEQ: compare(">="); break;
            case ImcBINOP::Oper::EQU: compare("="); break;
            case ImcBINOP::Oper::NEQ:
                emit(setLine(h, 0));
                emit("execute unless score " + score(a) + " = " + score(b) + " run " + truth);
                break;
            case ImcBINOP::Oper::AND:
                emit(setLine(h, 0));
                emit("execute unless score " + score(a) + " matches 0 unless score " + score(b)
                     + " matches 0 run " + truth);
                break;
            case ImcBINOP::Oper::OR:
                emit(truth);
                emit("execute if score " + score(a) + " matches 0 if score " + score(b) + " matches 0 run "
                     + setLine(h, 0));
                break;
        }
        m_holder = h;
    }

    // Strength reduction: x * k and x / k for a whole constant k. The general code
    // splits the fixed-point product so it can't overflow (7 commands), but with k
    // unscaled the result is just x*k or floor(x/k): 3 commands, and x*2 is x + x.
    bool McGen::multiplyByWhole(ImcBINOP &e) {
        if (e.oper != ImcBINOP::Oper::MUL && e.oper != ImcBINOP::Oper::DIV)
            return false;
        ImcExpr *operand = e.fst.get();
        auto *k = dynamic_cast<ImcCONST *>(e.snd.get());
        if (!k && e.oper == ImcBINOP::Oper::MUL) {
            k = dynamic_cast<ImcCONST *>(e.fst.get());
            operand = e.snd.get();
        }
        if (!k || dynamic_cast<ImcCONST *>(operand) || k->value != std::floor(k->value)
            || std::abs(k->value) > INT_MAX || (e.oper == ImcBINOP::Oper::DIV && k->value == 0))
            return false;

        const auto whole = static_cast<long long>(k->value);
        const std::string a = gen(*operand);
        const std::string h = scratch();
        copy(h, a);
        if (e.oper == ImcBINOP::Oper::MUL && whole == 2) {
            emit(opLine(h, "+=", a));
        } else if (whole != 1) {
            const std::string by = scratch();
            emit(setLine(by, whole));
            emit(opLine(h, e.oper == ImcBINOP::Oper::MUL ? "*=" : "/=", by));
        }
        m_holder = h;
        return true;
    }

    // The result is copied out of RV at once: the next call overwrites it.
    void McGen::visit(ImcCALL &e) {
        emitCall(e);
        m_holder = scratch();
        copy(m_holder, "$RV");
    }

    void McGen::visit(ImcSEXPR &) { error("SEXPR left in linearized code"); }

    // ---- statements ----------------------------------------------------------

    void McGen::visit(ImcMOVE &s) {
        if (auto *temp = dynamic_cast<ImcTEMP *>(s.dst.get())) {
            copy("$" + temp->temp.toString(), gen(*s.src));
            return;
        }

        auto *mem = dynamic_cast<ImcMEM *>(s.dst.get());
        if (!mem) {
            error("MOVE into neither a MEM nor a TEMP: " + s.toString());
            return;
        }

        // A call runs first: it clobbers every scratch holder.
        const bool isCall = dynamic_cast<ImcCALL *>(s.src.get()) != nullptr;
        std::string value = isCall ? gen(*s.src) : "";
        const std::string address = gen(*mem->addr);

        if (mem->size > SLOT_SIZE) {
            auto *source = dynamic_cast<ImcMEM *>(s.src.get());
            if (!source) {
                error("a record-sized MOVE from something not in memory: " + s.toString());
                return;
            }
            copySlots(address, gen(*source->addr), mem->size);
            return;
        }
        if (!isCall)
            value = gen(*s.src);
        store(address, value);
    }

    void McGen::visit(ImcESTMT &s) { gen(*s.expr); }

    // A command with no holes runs as it stands. One with holes becomes a function
    // macro: each value goes into storage mcl:args as a plain number -- a double,
    // so 37.5 arrives as 37.5 and 3 as 3 -- and the macro puts them into the text.
    //
    // When the value is kept, `execute store` catches the command's success or
    // result (a macro passes its command's back through `return run`), and it is
    // scaled into fixed point like every other number.
    void McGen::visit(ImcCMD &s) {
        std::string run = s.text;
        if (!s.args.empty()) {
            std::vector<std::string> holders(s.args.size());
            for (std::size_t i = 0; i < s.args.size(); ++i)
                if (!m_optimize || !dynamic_cast<ImcCONST *>(s.args[i].get()))
                    holders[i] = gen(*s.args[i]);

            for (std::size_t i = 0; i < holders.size(); ++i) {
                const std::string at = "storage mcl:args a" + std::to_string(i);
                if (const auto *c = dynamic_cast<ImcCONST *>(s.args[i].get()); m_optimize && c)
                    emit("data modify " + at + " set value " + decimal(c->value) + "d");
                else
                    emit("execute store result " + at + " double " + decimal(1.0 / SCALE)
                         + " run scoreboard players get " + score(holders[i]));
            }
            run = "function " + commandFile(s.text) + " with storage mcl:args";
        }

        if (!s.dst) {
            emit(run);
            return;
        }
        const std::string holder = "$" + s.dst->toString();
        emit("execute store " + std::string(s.store == ImcCMD::Store::Success ? "success" : "result") + " score "
             + score(holder) + " run " + run);
        emit(opLine(holder, "*=", "#scale"));
    }

    // One file per distinct command, shared by every place that runs it.
    std::string McGen::commandFile(const std::string &text) {
        auto it = m_commands.find(text);
        if (it != m_commands.end())
            return it->second;

        std::string macro; // the text with $(a0), $(a1), ... in its holes
        std::size_t arg = 0;
        for (std::size_t i = 0; i < text.size(); ++i) {
            if (text[i] == '{' && i + 1 < text.size() && text[i + 1] == '}') {
                macro += "$(a" + std::to_string(arg++) + ")";
                ++i;
                continue;
            }
            macro += text[i];
        }

        const std::string path = "rt/cmd" + std::to_string(m_commands.size());
        // `return run` hands the command's success and result back to the caller.
        m_files[path] = {"# Macro: " + text, "$return run " + macro};
        const std::string name = "mcl:" + path;
        m_commands[text] = name;
        return name;
    }

    void McGen::visit(ImcJUMP &s) {
        emit(jumpTo(s.label.name));
        m_terminated = true;
    }

    void McGen::visit(ImcCJUMP &s) {
        // Optimized, a comparison jumps on the comparison itself instead of first
        // turning it into 0 or 1000 and testing that.
        auto *compare = dynamic_cast<ImcBINOP *>(s.cond.get());
        const auto *wide = compare ? dynamic_cast<ImcMEM *>(compare->fst.get()) : nullptr;
        if (m_optimize && compare && !(wide && wide->size > SLOT_SIZE)) {
            using Oper = ImcBINOP::Oper;
            static const std::unordered_map<Oper, const char *> ops = {
                {Oper::LTH, "<"}, {Oper::GTH, ">"}, {Oper::LEQ, "<="}, {Oper::GEQ, ">="},
                {Oper::EQU, "="}, {Oper::NEQ, "="}};
            if (auto op = ops.find(compare->oper); op != ops.end()) {
                const std::string a = gen(*compare->fst);
                const std::string b = gen(*compare->snd);
                emit(std::string("execute ") + (compare->oper == Oper::NEQ ? "unless" : "if") + " score "
                     + score(a) + " " + op->second + " " + score(b) + " run " + jumpTo(s.pos.name));
                emit(jumpTo(s.neg.name));
                m_terminated = true;
                return;
            }
        }

        const std::string cond = gen(*s.cond);
        emit("execute unless score " + score(cond) + " matches 0 run " + jumpTo(s.pos.name));
        emit(jumpTo(s.neg.name));
        m_terminated = true;
    }

    void McGen::visit(ImcLABEL &) {} // genChunk starts a new block at every label

    void McGen::visit(ImcSTMTS &) { error("STMTS left in linearized code"); }
}
